apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=  # base64 encoded value of 'password'
  mysql-user-password: cGFzc3dvcmQ=  # base64 encoded value of 'password'
