apiVersion: v1
kind: Service

metadata:
  name: canary-service
  labels:
    app: canary-demo
spec:
  type: NodePort
  # type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http-port
      protocol: TCP
  selector:
    app: canary-demo
