---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: 483216680875.dkr.ecr.ap-south-1.amazonaws.com/hotstar:latest #apply rollback deployment after changing the version  
          ports:
            - name: http
              containerPort: 8181
          
