apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: demo
  labels:
      app: webapp
      type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx
