apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  type: NodePort
  selector:
    app: myapp
    replica: blue  #enables blue or green deployment to give access service here blue is nginx and green is httpd for our understanding
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
